//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Append_User
    {
        public int Id { get; set; }
        public Nullable<int> fromuid { get; set; }
        public string trueName { get; set; }
        public string phoneNumber { get; set; }
        public string IDnumber { get; set; }
    }
}
