//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public int uid { get; set; }
        public string userName { get; set; }
        public string trueName { get; set; }
        public string gender { get; set; }
        public string nativePlace { get; set; }
        public string loginEmail { get; set; }
        public string loginPWD { get; set; }
        public string phoneNumber { get; set; }
        public string IDnumber { get; set; }
        public byte[] headPhoto { get; set; }
    }
}
