//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class vehicle
    {
        public int id { get; set; }
        public int type { get; set; }
        public string startPlace { get; set; }
        public string endPlace { get; set; }
        public double price { get; set; }
        public System.DateTime startTime { get; set; }
        public Nullable<double> predictTime { get; set; }
        public int seats { get; set; }
        public int leftNote { get; set; }
    }
}
